# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install frontend
      run: |
        cd numerical_project
        npm install
    - name: install backend
      run: |
        cd backend
        npm install
    - name: test frontend
      run: |
        cd numerical_project
        npm test
    - name: test backend
      run: |
        cd backend
        npm test
    - name: test docker
      run: docker-compose build
